/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAiReplyRouteImport } from './routes/_authenticated/ai-reply'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedCompetitorsRouteImport } from './routes/_authenticated/competitors'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFaqRouteImport } from './routes/_authenticated/faq'
import { Route as AuthenticatedGmbRouteImport } from './routes/_authenticated/gmb'
import { Route as AuthenticatedQrRouteImport } from './routes/_authenticated/qr'
import { Route as AuthenticatedReviewsRouteImport } from './routes/_authenticated/reviews'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStandeesRouteImport } from './routes/_authenticated/standees'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated/whatsapp'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as ApiPublicKeywordRankCheckRouteImport } from './routes/api/public/keyword-rank-check'
import { Route as ApiPublicRatingDropAlertRouteImport } from './routes/api/public/rating-drop-alert'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'
import { Route as ApiPublicSubmitReviewRouteImport } from './routes/api/public/submit-review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiReplyRoute = AuthenticatedAiReplyRouteImport.update({
  id: '/ai-reply',
  path: '/ai-reply',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompetitorsRoute =
  AuthenticatedCompetitorsRouteImport.update({
    id: '/competitors',
    path: '/competitors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFaqRoute = AuthenticatedFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGmbRoute = AuthenticatedGmbRouteImport.update({
  id: '/gmb',
  path: '/gmb',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQrRoute = AuthenticatedQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewsRoute = AuthenticatedReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStandeesRoute = AuthenticatedStandeesRouteImport.update({
  id: '/standees',
  path: '/standees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKeywordRankCheckRoute =
  ApiPublicKeywordRankCheckRouteImport.update({
    id: '/api/public/keyword-rank-check',
    path: '/api/public/keyword-rank-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRatingDropAlertRoute =
  ApiPublicRatingDropAlertRouteImport.update({
    id: '/api/public/rating-drop-alert',
    path: '/api/public/rating-drop-alert',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSubmitReviewRoute = ApiPublicSubmitReviewRouteImport.update({
  id: '/api/public/submit-review',
  path: '/api/public/submit-review',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact-us': typeof ContactUsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai-reply': typeof AuthenticatedAiReplyRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/competitors': typeof AuthenticatedCompetitorsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/faq': typeof AuthenticatedFaqRoute
  '/gmb': typeof AuthenticatedGmbRoute
  '/qr': typeof AuthenticatedQrRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/standees': typeof AuthenticatedStandeesRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/r/$slug': typeof RSlugRoute
  '/api/public/keyword-rank-check': typeof ApiPublicKeywordRankCheckRoute
  '/api/public/rating-drop-alert': typeof ApiPublicRatingDropAlertRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/submit-review': typeof ApiPublicSubmitReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact-us': typeof ContactUsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai-reply': typeof AuthenticatedAiReplyRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/competitors': typeof AuthenticatedCompetitorsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/faq': typeof AuthenticatedFaqRoute
  '/gmb': typeof AuthenticatedGmbRoute
  '/qr': typeof AuthenticatedQrRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/standees': typeof AuthenticatedStandeesRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/r/$slug': typeof RSlugRoute
  '/api/public/keyword-rank-check': typeof ApiPublicKeywordRankCheckRoute
  '/api/public/rating-drop-alert': typeof ApiPublicRatingDropAlertRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/submit-review': typeof ApiPublicSubmitReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about-us': typeof AboutUsRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact-us': typeof ContactUsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ai-reply': typeof AuthenticatedAiReplyRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/competitors': typeof AuthenticatedCompetitorsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/faq': typeof AuthenticatedFaqRoute
  '/_authenticated/gmb': typeof AuthenticatedGmbRoute
  '/_authenticated/qr': typeof AuthenticatedQrRoute
  '/_authenticated/reviews': typeof AuthenticatedReviewsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/standees': typeof AuthenticatedStandeesRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/r/$slug': typeof RSlugRoute
  '/api/public/keyword-rank-check': typeof ApiPublicKeywordRankCheckRoute
  '/api/public/rating-drop-alert': typeof ApiPublicRatingDropAlertRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/submit-review': typeof ApiPublicSubmitReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/auth'
    | '/contact-us'
    | '/onboarding'
    | '/privacy-policy'
    | '/refund-policy'
    | '/reset-password'
    | '/terms-of-service'
    | '/admin'
    | '/ai-reply'
    | '/billing'
    | '/competitors'
    | '/dashboard'
    | '/faq'
    | '/gmb'
    | '/qr'
    | '/reviews'
    | '/settings'
    | '/standees'
    | '/whatsapp'
    | '/auth/callback'
    | '/r/$slug'
    | '/api/public/keyword-rank-check'
    | '/api/public/rating-drop-alert'
    | '/api/public/razorpay-webhook'
    | '/api/public/submit-review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/auth'
    | '/contact-us'
    | '/onboarding'
    | '/privacy-policy'
    | '/refund-policy'
    | '/reset-password'
    | '/terms-of-service'
    | '/admin'
    | '/ai-reply'
    | '/billing'
    | '/competitors'
    | '/dashboard'
    | '/faq'
    | '/gmb'
    | '/qr'
    | '/reviews'
    | '/settings'
    | '/standees'
    | '/whatsapp'
    | '/auth/callback'
    | '/r/$slug'
    | '/api/public/keyword-rank-check'
    | '/api/public/rating-drop-alert'
    | '/api/public/razorpay-webhook'
    | '/api/public/submit-review'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about-us'
    | '/auth'
    | '/contact-us'
    | '/onboarding'
    | '/privacy-policy'
    | '/refund-policy'
    | '/reset-password'
    | '/terms-of-service'
    | '/_authenticated/admin'
    | '/_authenticated/ai-reply'
    | '/_authenticated/billing'
    | '/_authenticated/competitors'
    | '/_authenticated/dashboard'
    | '/_authenticated/faq'
    | '/_authenticated/gmb'
    | '/_authenticated/qr'
    | '/_authenticated/reviews'
    | '/_authenticated/settings'
    | '/_authenticated/standees'
    | '/_authenticated/whatsapp'
    | '/auth/callback'
    | '/r/$slug'
    | '/api/public/keyword-rank-check'
    | '/api/public/rating-drop-alert'
    | '/api/public/razorpay-webhook'
    | '/api/public/submit-review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutUsRoute: typeof AboutUsRoute
  AuthRoute: typeof AuthRouteWithChildren
  ContactUsRoute: typeof ContactUsRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  RSlugRoute: typeof RSlugRoute
  ApiPublicKeywordRankCheckRoute: typeof ApiPublicKeywordRankCheckRoute
  ApiPublicRatingDropAlertRoute: typeof ApiPublicRatingDropAlertRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
  ApiPublicSubmitReviewRoute: typeof ApiPublicSubmitReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-reply': {
      id: '/_authenticated/ai-reply'
      path: '/ai-reply'
      fullPath: '/ai-reply'
      preLoaderRoute: typeof AuthenticatedAiReplyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/competitors': {
      id: '/_authenticated/competitors'
      path: '/competitors'
      fullPath: '/competitors'
      preLoaderRoute: typeof AuthenticatedCompetitorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faq': {
      id: '/_authenticated/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof AuthenticatedFaqRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gmb': {
      id: '/_authenticated/gmb'
      path: '/gmb'
      fullPath: '/gmb'
      preLoaderRoute: typeof AuthenticatedGmbRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qr': {
      id: '/_authenticated/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof AuthenticatedQrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reviews': {
      id: '/_authenticated/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/standees': {
      id: '/_authenticated/standees'
      path: '/standees'
      fullPath: '/standees'
      preLoaderRoute: typeof AuthenticatedStandeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/keyword-rank-check': {
      id: '/api/public/keyword-rank-check'
      path: '/api/public/keyword-rank-check'
      fullPath: '/api/public/keyword-rank-check'
      preLoaderRoute: typeof ApiPublicKeywordRankCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rating-drop-alert': {
      id: '/api/public/rating-drop-alert'
      path: '/api/public/rating-drop-alert'
      fullPath: '/api/public/rating-drop-alert'
      preLoaderRoute: typeof ApiPublicRatingDropAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/submit-review': {
      id: '/api/public/submit-review'
      path: '/api/public/submit-review'
      fullPath: '/api/public/submit-review'
      preLoaderRoute: typeof ApiPublicSubmitReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAiReplyRoute: typeof AuthenticatedAiReplyRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedCompetitorsRoute: typeof AuthenticatedCompetitorsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFaqRoute: typeof AuthenticatedFaqRoute
  AuthenticatedGmbRoute: typeof AuthenticatedGmbRoute
  AuthenticatedQrRoute: typeof AuthenticatedQrRoute
  AuthenticatedReviewsRoute: typeof AuthenticatedReviewsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStandeesRoute: typeof AuthenticatedStandeesRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAiReplyRoute: AuthenticatedAiReplyRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedCompetitorsRoute: AuthenticatedCompetitorsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFaqRoute: AuthenticatedFaqRoute,
  AuthenticatedGmbRoute: AuthenticatedGmbRoute,
  AuthenticatedQrRoute: AuthenticatedQrRoute,
  AuthenticatedReviewsRoute: AuthenticatedReviewsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStandeesRoute: AuthenticatedStandeesRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutUsRoute: AboutUsRoute,
  AuthRoute: AuthRouteWithChildren,
  ContactUsRoute: ContactUsRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  RSlugRoute: RSlugRoute,
  ApiPublicKeywordRankCheckRoute: ApiPublicKeywordRankCheckRoute,
  ApiPublicRatingDropAlertRoute: ApiPublicRatingDropAlertRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
  ApiPublicSubmitReviewRoute: ApiPublicSubmitReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
