// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


function getValidSupabaseUrl(): string {
  const DEFAULT_URL = "https://ltvzksmbrfnzcycknbqj.supabase.co";
  const candidates = [
    import.meta.env['VITE_SUPABASE_URL'],
    typeof process !== "undefined" ? process.env['VITE_SUPABASE_URL'] : undefined,
    typeof process !== "undefined" ? process.env['SUPABASE_URL'] : undefined,
  ];
  for (const c of candidates) {
    if (c && typeof c === "string" && c.trim().startsWith("http")) {
      return c.trim();
    }
  }
  return DEFAULT_URL;
}

function getValidSupabaseKey(): string {
  const DEFAULT_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0dnprc21icmZuemN5Y2tuYnFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODczNjQ1OTIsImV4cCI6MjEwMjk0MDU5Mn0.RMp3S9gX2epAMn9sSb8rzFJOUzL4gKraJmXc9Qe-s-4";
  const candidates = [
    import.meta.env['VITE_SUPABASE_PUBLISHABLE_KEY'],
    typeof process !== "undefined" ? process.env['VITE_SUPABASE_PUBLISHABLE_KEY'] : undefined,
    typeof process !== "undefined" ? process.env['SUPABASE_PUBLISHABLE_KEY'] : undefined,
  ];
  for (const c of candidates) {
    if (c && typeof c === "string" && c.trim().length > 10) {
      return c.trim();
    }
  }
  return DEFAULT_KEY;
}

function createSupabaseClient() {
  const url = getValidSupabaseUrl();
  const key = getValidSupabaseKey();

  return createClient<Database>(url, key, {
    global: {
      fetch: createSupabaseFetch(key),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

